CREATE TABLE "DB_DESIGN"."ACTIVITY"
(
"ACTIVITY_ID" INT NOT NULL,
"CLASS_ID" INT,
"NAME" VARCHAR(50),
"DATE" DATE,
NOT CLUSTER PRIMARY KEY("ACTIVITY_ID"),
FOREIGN KEY("CLASS_ID") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."ATTENDANCE"
(
"ATTENDANCEID" INT NOT NULL,
"CLASS_ID" INT,
"TIME" DATE,
NOT CLUSTER PRIMARY KEY("ATTENDANCEID"),
FOREIGN KEY("CLASS_ID") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."ATTENDANCE_STUDENT"
(
"ATTENDANCEID" INT NOT NULL,
"STUDENT_ID" INT NOT NULL,
"STATE" VARCHAR(50),
NOT CLUSTER PRIMARY KEY("ATTENDANCEID", "STUDENT_ID"),
FOREIGN KEY("ATTENDANCEID") REFERENCES "DB_Design"."ATTENDANCE"("ATTENDANCEID"),
FOREIGN KEY("STUDENT_ID") REFERENCES "DB_Design"."STUDENTS"("STUDENT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."CLASSES"
(
"classid" INT NOT NULL,
"classname" VARCHAR(50) NOT NULL,
NOT CLUSTER PRIMARY KEY("classid")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."CLASSLEADER"
(
"leaderid" INT NOT NULL,
"name" VARCHAR(50),
"position" VARCHAR(50),
"studentid" INT DEFAULT NULL,
"classid" INT,
NOT CLUSTER PRIMARY KEY("leaderid"),
FOREIGN KEY("classid") REFERENCES "DB_Design"."CLASSES"("CLASS_ID"),
CONSTRAINT "CONS134219047" FOREIGN KEY("studentid") REFERENCES "DB_DESIGN"."STUDENTS"("studentid")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."COMMENTS"
(
"COMMENT_ID" INT NOT NULL,
"HEADMASTER_ID" INT,
"COMMENT_CONTENT" TEXT,
NOT CLUSTER PRIMARY KEY("COMMENT_ID"),
FOREIGN KEY("HEADMASTER_ID") REFERENCES "DB_Design"."HEADMASTER"("HEADMASTER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."COURSES"
(
"COURSE_ID" INT NOT NULL,
"COURSE_NAME" VARCHAR(50) NOT NULL,
"COURSE_DESCRIPTION" TEXT,
"TEACHER_ID" INT,
NOT CLUSTER PRIMARY KEY("COURSE_ID"),
CONSTRAINT "FK_COURSE_TEACHER" FOREIGN KEY("TEACHER_ID") REFERENCES "DB_Design"."TEACHERS"("TEACHER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."COURSE_STUDENT"
(
"STUDENT_ID" INT NOT NULL,
"COURSE_ID" INT NOT NULL,
NOT CLUSTER PRIMARY KEY("STUDENT_ID", "COURSE_ID"),
FOREIGN KEY("STUDENT_ID") REFERENCES "DB_Design"."STUDENTS"("STUDENT_ID"),
FOREIGN KEY("COURSE_ID") REFERENCES "DB_Design"."COURSES"("COURSE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."DORMITORY"
(
"DORMITORY_ID" INT NOT NULL,
"CLASS_ID" INT,
"DORMITORY_NAME" VARCHAR(50) NOT NULL,
NOT CLUSTER PRIMARY KEY("DORMITORY_ID"),
FOREIGN KEY("CLASS_ID") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."DUTY"
(
"dutyid" INT NOT NULL,
"classid" INT,
"date" DATE NOT NULL,
"description" VARCHAR(100),
NOT CLUSTER PRIMARY KEY("dutyid"),
FOREIGN KEY("classid") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."DUTY_STUDENT"
(
"studentid" INT NOT NULL,
"dutyid" INT NOT NULL,
CONSTRAINT "FK_STUDENT" FOREIGN KEY("studentid") REFERENCES "DB_DESIGN"."STUDENTS"("studentid"),
CONSTRAINT "FK_DUTY" FOREIGN KEY("dutyid") REFERENCES "DB_DESIGN"."DUTY"("dutyid"),
NOT CLUSTER PRIMARY KEY("studentid", "dutyid")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."HEADMASTER"
(
"headmasterid" INT NOT NULL,
"username" VARCHAR(50) NOT NULL,
"password" VARCHAR(50) NOT NULL,
"classid" INT,
"role" VARCHAR(50),
NOT CLUSTER PRIMARY KEY("headmasterid"),
FOREIGN KEY("classid") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."PARAMETER"
(
"PARAMETER_ID" INT NOT NULL,
"HEADMASTER_ID" INT,
"PARAMETER_NAME" VARCHAR(50) NOT NULL,
"PARAMETER_VALUE" VARCHAR(50) NOT NULL,
NOT CLUSTER PRIMARY KEY("PARAMETER_ID"),
FOREIGN KEY("HEADMASTER_ID") REFERENCES "DB_Design"."HEADMASTER"("HEADMASTER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."PAYMENT"
(
"paymentid" INT NOT NULL,
"classid" INT,
"studentid" INT,
"paymentamount" DECIMAL(10,2) NOT NULL,
"paymentdate" DATE NOT NULL,
NOT CLUSTER PRIMARY KEY("paymentid"),
FOREIGN KEY("classid") REFERENCES "DB_Design"."CLASSES"("CLASS_ID"),
FOREIGN KEY("studentid") REFERENCES "DB_Design"."STUDENTS"("STUDENT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."REWARDPUNISHMENT"
(
"REWARD_PUNISHMENT_ID" INT NOT NULL,
"CLASS_ID" INT,
"REWARD_PUNISHMENT_DESCRIPTION" VARCHAR(100) NOT NULL,
"REWARD_PUNISHMENT_DATE" DATE NOT NULL,
NOT CLUSTER PRIMARY KEY("REWARD_PUNISHMENT_ID"),
FOREIGN KEY("CLASS_ID") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."STUDENTS"
(
"studentid" INT NOT NULL,
"name" VARCHAR(50) NOT NULL,
"age" INT,
"gender" VARCHAR(10),
"ethnicity" VARCHAR(50),
"politicalstatus" VARCHAR(50),
"position" VARCHAR(50),
"classid" INT,
"dormitoryid" INT,
NOT CLUSTER PRIMARY KEY("studentid"),
CONSTRAINT "FK_STUDENTS_CLASS" FOREIGN KEY("classid") REFERENCES "DB_Design"."CLASSES"("CLASS_ID"),
CONSTRAINT "FK_STUDENTS_DORMITORY" FOREIGN KEY("dormitoryid") REFERENCES "DB_Design"."DORMITORY"("DORMITORY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."SYS_MENU"
(
"id" INT,
"name" VARCHAR(255),
"path" VARCHAR(255),
"icon" VARCHAR(255),
"desciption" VARCHAR(255),
"pid" INT,
"page_path" VARCHAR(255),
"sort_num" INT) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."SYS_ROLE"
(
"id" INT NOT NULL,
"name" VARCHAR(50),
"flag" VARCHAR(50),
NOT CLUSTER PRIMARY KEY("id")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."SYS_ROLE_MENU"
(
"role_id" INT,
"menu_id" INT) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."TALKINGRECORD"
(
"RECORD_ID" INT NOT NULL,
"HEADMASTER_ID" INT,
"STUDENT_ID" INT,
"RECORD_DATE" DATE NOT NULL,
"RECORD_CONTENT" TEXT,
NOT CLUSTER PRIMARY KEY("RECORD_ID"),
FOREIGN KEY("HEADMASTER_ID") REFERENCES "DB_Design"."HEADMASTER"("HEADMASTER_ID"),
FOREIGN KEY("STUDENT_ID") REFERENCES "DB_Design"."STUDENTS"("STUDENT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."TEACHERS"
(
"TEACHER_ID" INT NOT NULL,
"NAME" VARCHAR(50) NOT NULL,
"GENDER" VARCHAR(10),
"POSITION" VARCHAR(50),
NOT CLUSTER PRIMARY KEY("TEACHER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."THEMEMEETING"
(
"MEETING_ID" INT NOT NULL,
"HEADMASTER_ID" INT,
"CLASS_ID" INT,
"MEETING_DATE" DATE NOT NULL,
"MEETING_TOPIC" VARCHAR(100) NOT NULL,
NOT CLUSTER PRIMARY KEY("MEETING_ID"),
FOREIGN KEY("HEADMASTER_ID") REFERENCES "DB_Design"."HEADMASTER"("HEADMASTER_ID"),
FOREIGN KEY("CLASS_ID") REFERENCES "DB_Design"."CLASSES"("CLASS_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."WORKPLAN"
(
"PLAN_ID" INT NOT NULL,
"HEADMASTER_ID" INT,
"PLAN_DATE" DATE NOT NULL,
"PLAN_CONTENT" TEXT,
NOT CLUSTER PRIMARY KEY("PLAN_ID"),
FOREIGN KEY("HEADMASTER_ID") REFERENCES "DB_Design"."HEADMASTER"("HEADMASTER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_DESIGN"."WORKSUMMARY"
(
"SUMMARY_ID" INT NOT NULL,
"HEADMASTER_ID" INT,
"SUMMARY_DATE" DATE NOT NULL,
"SUMMARY_CONTENT" TEXT,
NOT CLUSTER PRIMARY KEY("SUMMARY_ID"),
FOREIGN KEY("HEADMASTER_ID") REFERENCES "DB_Design"."HEADMASTER"("HEADMASTER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE SEQUENCE "DB_DESIGN"."LEADERID_SEQ" INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 MINVALUE 1;

